# Generated by Django 5.2.16 on 2026-07-22 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depots', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('external_ref', models.CharField(max_length=100)),
                ('order_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup'), ('PICKUP_DELIVERY', 'Pickup and delivery')], default='DELIVERY', max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('PLANNED', 'Planned'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('PARTIALLY_COMPLETED', 'Partially completed'), ('UNASSIGNED', 'Unassigned')], default='DRAFT', max_length=24)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('service_date', models.DateField()),
                ('time_window_start', models.DateTimeField(blank=True, null=True)),
                ('time_window_end', models.DateTimeField(blank=True, null=True)),
                ('service_duration_seconds', models.PositiveIntegerField(default=300)),
                ('demand_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('demand_volume_m3', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('package_count', models.PositiveIntegerField(default=1)),
                ('required_skills_json', models.JSONField(blank=True, default=list)),
                ('special_instructions', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'permissions': [('cancel_order', 'Can cancel order')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=180)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volume_m3', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderTimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('preference_weight', models.PositiveIntegerField(default=1)),
                ('hard_constraint', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='imports/%Y/%m/')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('accepted_rows', models.PositiveIntegerField(default=0)),
                ('rejected_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='depots.depot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('raw_data', models.JSONField(default=dict)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='orders.importjob')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
