# Generated by Django 5.2.16 on 2026-07-22 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('depots', '0002_initial'),
        ('drivers', '0001_initial'),
        ('orders', '0001_initial'),
        ('organizations', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_route_stop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_order', to='planning.routestop'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='customers.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='depots.depot'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_orders', to='customers.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_orders', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordertimewindow',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_windows', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'service_date', 'status'], name='orders_orde_organiz_f7fccc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['depot', 'service_date', 'status'], name='orders_orde_depot_i_a4958a_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('organization', 'external_ref'), name='uq_order_ref'),
        ),
    ]
