# Generated by Django 5.2.16 on 2026-07-22 01:43

import apps.common.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=24)),
                ('country_code', models.CharField(max_length=2)),
                ('formatted_address', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('geocode_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('AMBIGUOUS', 'Ambiguous'), ('INVALID', 'Invalid'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('geocode_provider', models.CharField(blank=True, max_length=40)),
                ('geocode_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('access_notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=180)),
                ('email_encrypted', apps.common.fields.EncryptedTextField(blank=True, default='')),
                ('phone_encrypted', apps.common.fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_hash', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=40)),
                ('formatted_address', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
