# Generated by Django 5.2.16 on 2026-07-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depots', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='restrictedzone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_zones', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='depot',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_depot_code'),
        ),
    ]
