# Generated by Django 5.2.16 on 2026-07-22 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exceptions', '0001_initial'),
        ('orders', '0001_initial'),
        ('organizations', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationexception',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='operationexception',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='operationexception',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationexception',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='planning.route'),
        ),
        migrations.AddField(
            model_name='operationexception',
            name='route_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='planning.routestop'),
        ),
        migrations.AddIndex(
            model_name='operationexception',
            index=models.Index(fields=['organization', 'status', 'severity', 'created_at'], name='exceptions__organiz_a496f9_idx'),
        ),
    ]
