# Generated by Django 5.2.16 on 2026-07-22 01:43

import apps.common.fields
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depots', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('employee_code', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=180)),
                ('phone_encrypted', apps.common.fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_ROUTE', 'On route'), ('OFF_DUTY', 'Off duty'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('skills_json', models.JSONField(blank=True, default=list)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='depots.depot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='organizations.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=120)),
                ('refresh_jti', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_date', models.DateField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('start_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('break_rules_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=16)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='drivers.driver')),
            ],
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_code'), name='uq_driver_code'),
        ),
        migrations.AddConstraint(
            model_name='driverdevice',
            constraint=models.UniqueConstraint(fields=('driver', 'device_id'), name='uq_driver_device'),
        ),
        migrations.AddConstraint(
            model_name='drivershift',
            constraint=models.UniqueConstraint(fields=('driver', 'shift_date', 'start_at'), name='uq_driver_shift'),
        ),
    ]
