# Generated by Django 5.2.16 on 2026-07-22 01:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        ('organizations', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payload_json', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='drivers.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_events', to='organizations.organization')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planning.route')),
                ('route_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='planning.routestop')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['route', 'occurred_at'], name='tracking_dr_route_i_4b81fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('driver', 'idempotency_key'), name='uq_driver_event_key')],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed_kph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('source', models.CharField(default='driver_web', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='drivers.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_locations', to='organizations.organization')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='planning.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vehicle', 'recorded_at'], name='tracking_ve_vehicle_7d3cde_idx')],
            },
        ),
    ]
