# Generated by Django 5.2.16 on 2026-07-22 01:43

import apps.proof_of_delivery.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(blank=True, max_length=180)),
                ('recipient_relation', models.CharField(blank=True, max_length=100)),
                ('signature_file', models.FileField(blank=True, null=True, upload_to=apps.proof_of_delivery.models.pod_upload_path)),
                ('photo_file', models.ImageField(blank=True, null=True, upload_to=apps.proof_of_delivery.models.pod_upload_path)),
                ('note', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField()),
                ('captured_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('route_stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_delivery', to='planning.routestop')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
