# Generated by Django 5.2.16 on 2026-07-22 01:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depots', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=40)),
                ('plate_number', models.CharField(max_length=40)),
                ('vehicle_type', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In use'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('capacity_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('capacity_volume_m3', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('capacity_package_count', models.PositiveIntegerField(default=0)),
                ('max_stops', models.PositiveIntegerField(default=100)),
                ('max_route_duration_seconds', models.PositiveIntegerField(default=43200)),
                ('skills_json', models.JSONField(blank=True, default=list)),
                ('start_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_per_km', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cost_per_hour', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='depots.depot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_periods', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_vehicle_code'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('organization', 'plate_number'), name='uq_vehicle_plate'),
        ),
    ]
