# Generated by Django 5.2.16 on 2026-07-22 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Organization Admin'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('DISPATCHER', 'Dispatcher'), ('FLEET_MANAGER', 'Fleet Manager'), ('DRIVER', 'Driver'), ('CUSTOMER_SERVICE', 'Customer Service'), ('AUDITOR', 'Auditor')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('depots', models.ManyToManyField(blank=True, related_name='authorized_memberships', to='depots.depot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='uq_org_membership')],
            },
        ),
    ]
